### ISSUE TITLE
Code formatting breaks the bundle

### ISSUE THREAD

**Issue by virtua-slash-admin** [shopwareLabs/SwagAdvDevBundle#1]
Greetings! 
By default, my IDE (PHPStorm) removes spaces, so the code from this file:

https://github.com/shopwareLabs/SwagAdvDevBundle/blob/master/Resources/views/backend/swag_bundle/model/bundle.js

transforms from this: 
```
fields: [
        { name: 'id', type: 'int', useNull: true },
        { name: 'name', type: 'string' },
        { name: 'active', type: 'boolean' }
    ]
```
to this:
```
fields: [
        {name: 'id', type: 'int', useNull: true},
        {name: 'name', type: 'string'},
        {name: 'active', type: 'boolean'}
    ]
```
And such change breaks the whole bundle, this is what is shown in the admin panel:
![issue](https://user-images.githubusercontent.com/54265429/64535225-2cc00100-d317-11e9-8a48-522df6923ba7.jpg)
Is this the intended behavior? 
Thanks!

**Comment by mitelg** [comment]
hey @dimitri-virtua 
this is because of the Smarty parsing.
Each ExtJS file is parsed by Smarty, so that we could use things like snippets functionality, etc. 
Because of that, `{name` will be interpreted by Smarty, and as this is an invalid Smarty function, the error occurs. 

You should set the following code style rule:
Settings -> Editor -> Code Style -> JavaScript -> Spaces -> Within -> Object literal braces

**Comment by virtua-slash-admin** [comment]
@mitelg thanks for the information!
